/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPublishIndexRouteImport } from './routes/app.publish.index'
import { Route as AppMeIndexRouteImport } from './routes/app.me.index'
import { Route as AppVoiceIdRouteImport } from './routes/app.voice.$id'
import { Route as AppPublishSuccessRouteImport } from './routes/app.publish.success'
import { Route as AppPublishPreviewRouteImport } from './routes/app.publish.preview'
import { Route as AppPublishBackgroundRouteImport } from './routes/app.publish.background'
import { Route as AppMeVoicesRouteImport } from './routes/app.me.voices'
import { Route as AppMeEditRouteImport } from './routes/app.me.edit'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishIndexRoute = AppPublishIndexRouteImport.update({
  id: '/publish/',
  path: '/publish/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeIndexRoute = AppMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceIdRoute = AppVoiceIdRouteImport.update({
  id: '/voice/$id',
  path: '/voice/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishSuccessRoute = AppPublishSuccessRouteImport.update({
  id: '/publish/success',
  path: '/publish/success',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishPreviewRoute = AppPublishPreviewRouteImport.update({
  id: '/publish/preview',
  path: '/publish/preview',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishBackgroundRoute = AppPublishBackgroundRouteImport.update({
  id: '/publish/background',
  path: '/publish/background',
  getParentRoute: () => AppRoute,
} as any)
const AppMeVoicesRoute = AppMeVoicesRouteImport.update({
  id: '/me/voices',
  path: '/me/voices',
  getParentRoute: () => AppRoute,
} as any)
const AppMeEditRoute = AppMeEditRouteImport.update({
  id: '/me/edit',
  path: '/me/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/me/edit': typeof AppMeEditRoute
  '/app/me/voices': typeof AppMeVoicesRoute
  '/app/publish/background': typeof AppPublishBackgroundRoute
  '/app/publish/preview': typeof AppPublishPreviewRoute
  '/app/publish/success': typeof AppPublishSuccessRoute
  '/app/voice/$id': typeof AppVoiceIdRoute
  '/app/me/': typeof AppMeIndexRoute
  '/app/publish/': typeof AppPublishIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
  '/app/me/edit': typeof AppMeEditRoute
  '/app/me/voices': typeof AppMeVoicesRoute
  '/app/publish/background': typeof AppPublishBackgroundRoute
  '/app/publish/preview': typeof AppPublishPreviewRoute
  '/app/publish/success': typeof AppPublishSuccessRoute
  '/app/voice/$id': typeof AppVoiceIdRoute
  '/app/me': typeof AppMeIndexRoute
  '/app/publish': typeof AppPublishIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/me/edit': typeof AppMeEditRoute
  '/app/me/voices': typeof AppMeVoicesRoute
  '/app/publish/background': typeof AppPublishBackgroundRoute
  '/app/publish/preview': typeof AppPublishPreviewRoute
  '/app/publish/success': typeof AppPublishSuccessRoute
  '/app/voice/$id': typeof AppVoiceIdRoute
  '/app/me/': typeof AppMeIndexRoute
  '/app/publish/': typeof AppPublishIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/profile'
    | '/app/'
    | '/app/me/edit'
    | '/app/me/voices'
    | '/app/publish/background'
    | '/app/publish/preview'
    | '/app/publish/success'
    | '/app/voice/$id'
    | '/app/me/'
    | '/app/publish/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/profile'
    | '/app'
    | '/app/me/edit'
    | '/app/me/voices'
    | '/app/publish/background'
    | '/app/publish/preview'
    | '/app/publish/success'
    | '/app/voice/$id'
    | '/app/me'
    | '/app/publish'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/profile'
    | '/app/'
    | '/app/me/edit'
    | '/app/me/voices'
    | '/app/publish/background'
    | '/app/publish/preview'
    | '/app/publish/success'
    | '/app/voice/$id'
    | '/app/me/'
    | '/app/publish/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publish/': {
      id: '/app/publish/'
      path: '/publish'
      fullPath: '/app/publish/'
      preLoaderRoute: typeof AppPublishIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me/': {
      id: '/app/me/'
      path: '/me'
      fullPath: '/app/me/'
      preLoaderRoute: typeof AppMeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voice/$id': {
      id: '/app/voice/$id'
      path: '/voice/$id'
      fullPath: '/app/voice/$id'
      preLoaderRoute: typeof AppVoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publish/success': {
      id: '/app/publish/success'
      path: '/publish/success'
      fullPath: '/app/publish/success'
      preLoaderRoute: typeof AppPublishSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publish/preview': {
      id: '/app/publish/preview'
      path: '/publish/preview'
      fullPath: '/app/publish/preview'
      preLoaderRoute: typeof AppPublishPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publish/background': {
      id: '/app/publish/background'
      path: '/publish/background'
      fullPath: '/app/publish/background'
      preLoaderRoute: typeof AppPublishBackgroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me/voices': {
      id: '/app/me/voices'
      path: '/me/voices'
      fullPath: '/app/me/voices'
      preLoaderRoute: typeof AppMeVoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me/edit': {
      id: '/app/me/edit'
      path: '/me/edit'
      fullPath: '/app/me/edit'
      preLoaderRoute: typeof AppMeEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMeEditRoute: typeof AppMeEditRoute
  AppMeVoicesRoute: typeof AppMeVoicesRoute
  AppPublishBackgroundRoute: typeof AppPublishBackgroundRoute
  AppPublishPreviewRoute: typeof AppPublishPreviewRoute
  AppPublishSuccessRoute: typeof AppPublishSuccessRoute
  AppVoiceIdRoute: typeof AppVoiceIdRoute
  AppMeIndexRoute: typeof AppMeIndexRoute
  AppPublishIndexRoute: typeof AppPublishIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppMeEditRoute: AppMeEditRoute,
  AppMeVoicesRoute: AppMeVoicesRoute,
  AppPublishBackgroundRoute: AppPublishBackgroundRoute,
  AppPublishPreviewRoute: AppPublishPreviewRoute,
  AppPublishSuccessRoute: AppPublishSuccessRoute,
  AppVoiceIdRoute: AppVoiceIdRoute,
  AppMeIndexRoute: AppMeIndexRoute,
  AppPublishIndexRoute: AppPublishIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
